src/Entity/Ouvrage.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use phpDocumentor\Reflection\DocBlock\Tags\Author;

/**
 * @ORM\Entity(repositoryClass="App\Repository\OuvrageRepository")
 */
class Ouvrage
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $Numero;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Auteur")
     * @ORM\JoinColumn(name="Auteur_id", referencedColumnName="id", onDelete="SET NULL", nullable=true)
     */
    private $Auteur_id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Titre;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Theme")
     * @ORM\JoinColumn(name="Theme_id", referencedColumnName="id", onDelete="SET NULL", nullable=true)  
     */
    private $Theme_id;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumero()
    {
        return $this->Numero;
    }

    public function setNumero($Numero): self
    {
        $this->Numero = $Numero;

        return $this;
    }

    public function getAuteurId()
    {
        if($this->Auteur_id == null){
            return null;
        }
        return $this->Auteur_id;
    }

    public function setAuteurId($Auteur_id): self
    {
        $this->Auteur_id = $Auteur_id;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->Titre;
    }

    public function setTitre(string $Titre): self
    {
        $this->Titre = $Titre;

        return $this;
    }

    public function getThemeId()
    {
        if($this->Theme_id == null){
            return null;
        }
        return $this->Theme_id;
    }

    public function setThemeId($Theme_id): self
    {
        $this->Theme_id = $Theme_id;

        return $this;
    }
}

src/Entity/Theme.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ThemeRepository")
 */
class Theme
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Libelle;

    public function getId()
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->Libelle;
    }

    public function setLibelle(string $Libelle): self
    {
        $this->Libelle = $Libelle;

        return $this;
    }


}

src/Controller/CatalogueController.php
<?php

namespace App\Controller;

use App\Entity\Ouvrage;
use App\Entity\User;
use App\Repository\AuteurRepository;
use App\Repository\ThemeRepository;
use Knp\Component\Pager\PaginatorInterface;
use phpDocumentor\Reflection\Types\String_;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpFoundation\Request;
use App\Repository\UserRepository;
use App\Repository\OuvrageRepository;
use App\Form\OuvrageType;

use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;

class CatalogueController extends AbstractController
{
    /**
     * @var OuvrageRepository
     */
    private $repository;
    private $repo;
    private $em;
    public $user;
    private $repoTheme;
    private $repoAuteur;

    public function __construct(OuvrageRepository $repository, ObjectManager $em, UserRepository $repo, ThemeRepository $repoTheme, AuteurRepository $repoAuteur)
    {
        $this->repoAuteur = $repoAuteur;
        $this->repoTheme = $repoTheme;
        $this->repository = $repository;
        $this->em = $em;
        $this->repo = $repo;
        $_SESSION['email'] = "test@gmail.com";
        if ($_SESSION['email'] != null) {
            $test1 = $this->repo->findByMail($_SESSION['email']);
            if ($test1 == []) {
                $this->user = new User();
                $test = $this->repo->findByRole('ROLE_ADMIN');
                $this->user->setEmail($_SESSION['email']);
                if (in_array($this->user->getEmail(), $test)) {
                    $this->user->setRole("ROLE_ADMIN");
                } else {
                    $this->user->setRole("ROLE_USER");
                }
                $this->em->persist($this->user);
                $this->em->flush();
            } else {
                $this->user = $test1[0];
            }
        } else {
            return $this->redirectToRoute("home");
        }

    }

    /**
     * @return Response
     */
    public function index(PaginatorInterface $paginator, Request $request): Response
    {
        $ouvrage = $paginator->paginate(
            $this->repository->findAllQuerry(),
            $request->query->getInt('page', 1),
            12
        );
        $theme = $this->repoTheme->findAll();
        $auteur = $this->repoAuteur->findAll();
        $newOuvrage = new Ouvrage();
        $form = $this->createForm(OuvrageType::class, $newOuvrage);
        $form->handleRequest($request);
        $str = "drama";
        $search = $this->createFormBuilder()
            ->add('search', TextType::class)
            ->getForm();
        if ($search->isSubmitted() && $search->isValid()){
            $ouvrage = $paginator->paginate(
                $this->repository->search($str),
                $request->query->getInt('page', 1),
                12
            );
        }

        if ($form->isSubmitted() && $form->isValid()) {
            $this->em->persist($newOuvrage);
            $this->em->flush();
            return $this->redirectToRoute("catalogue");
        }
        dump($ouvrage);
        return $this->render("catalogue/catalogue.html.twig",
            [
                'ouvrages' => $ouvrage,
                'user' => $this->user,
                'theme' => $theme,
                'auteur' => $auteur,
                'forms' => $form->createView(),
                'search' => $search->createView()
            ]);
    }


    public function del(Request $request): Response
    {
        if ($this->user->getRole() == "ROLE_ADMIN") {
            $id = $request->query->get('id');
            $ouvrage = $this->repository->find($id);
            $this->em->remove($ouvrage);
            $this->em->flush();
            return $this->render("Home/Home.html.twig");
        }
    }
    public function edit(Request $request): Response
    {
        if ($this->user->getRole() == "ROLE_ADMIN") {
            $id = $request->query->get('id');
            $numero = $request->query->get('num');
            $titre = $request->query->get('titre');
            $themeId = $request->query->get('themeId');
            $auteurId= $request->query->get('auteurId');
            $themeId = $this->repoTheme->find($themeId);
            $auteurId = $this->repoAuteur->find($auteurId);
            dump($themeId, $auteurId);
            $ouvrage = $this->repository->find($id);
            $ouvrage->setTitre($titre);
            $ouvrage->setNumero($numero);
            $ouvrage->setAuteurId($auteurId);
            $ouvrage->setThemeId($themeId);
            dump($ouvrage);
            $this->em->flush();
            return $this->render("Home/Home.html.twig");
        }
    }
}

templates/catalogue/catalogue.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <table class="table table-striped">
        <thead>
        {% if user.role == 'ROLE_ADMIN' %}
        <tr><th scope="row" class="col-24">  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#addModal">
                    Ajout Ouvrage
                </button></th></tr>
        {% endif %}
            <tr>
                <th scope="col" class="col-1">{{ knp_pagination_sortable(ouvrages, 'Numero','o.Numero') }}</th>
                <th scope="col" class="col-2">{{ knp_pagination_sortable(ouvrages, 'Titre','o.Titre') }}</th>
                <th scope="col" class="col-2">{{ knp_pagination_sortable(ouvrages, 'Theme','o.Theme_id') }}</th>
                <th scope="col" class="col-3">Auteur</th>
                <th scope="col" class="col-4">Action</th>
            </tr>
        </thead>
        <tbody>
            {% for ouvrage in ouvrages %}
                <tr>
                    {% if user.role != 'ROLE_ADMIN' %}
                    <th scope="row">{{ ouvrage.numero }}</th>
                    <td>{{ ouvrage.titre }}</td>
                    <td>{% if ouvrage.themeId is null %}{{null}}{% else %}{{ ouvrage.themeId.libelle }}{% endif %}</td>
                    <td>{% if ouvrage.auteurId is null %}{{null}}{% else %}{{ ouvrage.auteurId.libelle }}{% endif %} </td>
                    {% endif %}
                    {% if user.role == 'ROLE_ADMIN' %}
                        <td scope="row"><input type = "text" value="{{ ouvrage.numero }}" disabled="disabled" id="num{{ ouvrage.id}}" class="show_input"> </td>
                        <td scope="row"><input type = "text" value="{{ ouvrage.titre }}" disabled="disabled" id="titre{{ ouvrage.id}}" class="show_input"> </td>
                        <td scope="row">
                            <select disabled="disabled" id="theme{{ ouvrage.id}}" class="show_input">
                                <option value="{% if ouvrage.themeId is null %}{{null}}{% else %}{{ ouvrage.themeId.id }}{% endif %}">{% if ouvrage.themeId is null %}{{null}}{% else %}{{ ouvrage.themeId.libelle }}{% endif %}</option>
                                    {% for themes in theme %}
                                <option value="{{ themes.id }}">{{ themes.libelle }}</option>
                                    {% endfor %}

                            </select>
                        </td>
                        <td scope="row"> <select disabled="disabled" id="auteur{{ ouvrage.id}}" class="show_input">
                                <option value="{% if ouvrage.auteurId is null %}{{null}}{% else %}{{ ouvrage.auteurId.id }}{% endif %}">{% if ouvrage.auteurId is null %}{{null}}{% else %}{{ ouvrage.auteurId.libelle }}{% endif %}</option>
                                {% for auteurs in auteur %}
                                    <option value="{{ auteurs.id }}">{{ auteurs.libelle }}</option>
                                {% endfor %}

                            </select>
                        <td>
                            <button type="button" class="btn btn-secondary" id="btn_update{{ ouvrage.id }}" onclick="unlock({{ ouvrage.id }});">
                                Modifier
                            </button>

                            <button type="button" class="btn btn-danger" id="btn_del{{ ouvrage.id }}" onclick="suppression({{ ouvrage.id }});">
                                Supprimer
                            </button>

                            <button type="button" class="btn btn-secondary hide" id="btn_cancel{{ ouvrage.id }}" onclick="lock({{ ouvrage.id }});">
                                Annuler
                            </button>
                            <button type="button" class="btn btn-primary hide" id="btn_valid{{ ouvrage.id }}" onclick="modif({{ ouvrage.id }});">
                                Valider
                            </button>
                        </td>
                    {% endif %}
                </tr>

            {% endfor %}
            <td>
                {{ knp_pagination_render(ouvrages) }}
            </td>
        </tbody>
    </table>
    </table>
    {% if user.role == 'ROLE_ADMIN' %}

        <!-- modal ajout-->

        <div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Ajout</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    {{ form_start(forms) }}
                    <div class="modal-body">

                        {{ form_rest(forms) }}

                        <button class="btn btn-primary">Confirmer</button>
                        {{ form_end(forms) }}
                    </div>

                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}
{% block javascripts %}
    <script>
        $(".show_input").attr("disabled",true);
    </script>
    <script src="{{ asset('JS/indexOuvrage.js') }}"></script>
{% endblock %}